export const environment = {
  production: true,
  casperRPC: 'https://node-clarity-testnet.make.services/rpc',
  casperEnv: 'casper-test',
  bcGasFeesMin: 0, //minimum fees for the transaction with the blockchain
  bcGasFeesMax: 5, //maximum fees for the transaction with the blockchain
  bcGasFeesAsDefault: 1.5, // default fees for the transaction with the blockchain (can be changed within the app)
  version: "dc03e7c" // Version of the app, autogenerated when calling the build --prod
};
